name: demo
run-name: ${{github.actor}} is testing out Github Actions
on: push
jobs:
    explore-github-actions:
        runs-on: Ubuntu-latest
        steps:
            - name: Welcome
              run: echo "demo is running on ${{runner.os}}, the repository is ${{github.repository}}, the branch is ${{github.ref}}, is trigger by ${{github.event_name}} event"
            - name: Checkout
              uses: actions/checkout@v4
            - name: List files
              run: ls ${{github.workspace}}