name: doc lint
on:
    pull_request:
        branches: [main]
        paths:
            - '*.md'
jobs:
    mis-spell:
        runs-on: Ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Checking misspell
              uses: reviewdog/action-misspell@1.21.0